### ISSUE TITLE
[Release]: v0.7.0 Release Tracker

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#11218]
We plan a release after V1 is ready. 

~Planned release Dec 16-17.~

We do not block release on feature request, minor issues. We do block release on major feature development, important user impacting issues, and compatibility fixes. 

Add pending PRs directly here ⬇️ 

- [x] https://github.com/vllm-project/vllm/pull/10511
- [x] #11210

**Comment by youkaichao** [comment]
- [ ] https://github.com/vllm-project/vllm/pull/11108 cc @tlrmchlsmth

**Comment by robertgshaw2-neuralmagic** [comment]
- [ ] https://github.com/vllm-project/vllm/pulls?q=cutlass+2%3A4

**Comment by Jeffwan** [comment]
https://github.com/vllm-project/vllm/pull/11117 I will try to polish this change by end of tomorrow. If I can not make it on time, feel free to skip

**Comment by simon-mo** [comment]
@khluu and I will make a v0.6.5 release for now given we haven't released for 30 days. We will release v0.7.0 when V1 is ready.

**Comment by JaheimLee** [comment]
> @khluu and I will make a v0.6.5 release for now given we haven't released for 30 days. We will release v0.7.0 when V1 is ready.

Can we try V1 in v0.6.5 now? And how to use it?

**Comment by xfalcox** [comment]
> @khluu and I will make a v0.6.5 release for now given we haven't released for 30 days. We will release v0.7.0 when V1 is ready.

That would be lovely. The bug fixed at #10511 is heavily impacting, and I'd love a new docker image to fix it.

**Comment by youkaichao** [comment]
@xfalcox the docker image is updated to 0.6.5 in https://hub.docker.com/r/vllm/vllm-openai/tags
