### ISSUE TITLE
v0.4.3 Release Tracker

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#4895]
ETA May 30 (due to some blockers and US holiday). 

Blockers
- [ ] #4650
- [ ] #4799
- [x] #4846

Nice to have
- [ ] #4638
- [x] #4525
- [ ] #4464

**Comment by sasha0552** [comment]
Hi, is it possible to include the following PRs?
* #4167
* #4409
* #4638

**Comment by simon-mo** [comment]
Thanks for bring these up @sasha0552!

#4167 is unlikely to be finished in time. 
#4409 might need a little bit more discussion given what features are supported for Pascal GPUs and whether building from source might be a better option. 
#4638 can be included if it gets merged in time. 

We do commit to biweekly release cadence so don't worry many of these will get into soon enough!

**Comment by robertgshaw2-neuralmagic** [comment]
> Thanks for bring these up @sasha0552!
> 
> #4167 is unlikely to be finished in time. #4409 might need a little bit more discussion given what features are supported for Pascal GPUs and whether building from source might be a better option. #4638 can be included if it gets merged in time.
> 
> We do commit to biweekly release cadence so don't worry many of these will get into soon enough!

re: #4409 --> I did not have any issues running an fp16 model on a P40 when I installed from source.

**Comment by robertgshaw2-neuralmagic** [comment]
we should get these in:
- [ ] https://github.com/vllm-project/vllm/pull/4846
- [ ] https://github.com/vllm-project/vllm/pull/4525
- [ ] https://github.com/vllm-project/vllm/pull/4442
- [ ] https://github.com/vllm-project/vllm/pull/4464

probably will not make it but tracking to v0.4.4:
- [ ] https://github.com/vllm-project/vllm/pull/4582
- [ ] https://github.com/vllm-project/vllm/pull/4442

**Comment by njhill** [comment]
Sounds like we may want to include https://github.com/vllm-project/vllm/pull/4894 @rkooo567?

**Comment by rkooo567** [comment]
Yeah +1 on that PR @njhill

**Comment by robertgshaw2-neuralmagic** [comment]
Mistral v3 is broken. Working on a fix

**Comment by jasonacox** [comment]
> re: https://github.com/vllm-project/vllm/pull/4409 --> I did not have any issues running an fp16 model on a P40 when I installed from source.

Hi @robertgshaw2-neuralmagic - was this without the patch? I couldn't get a source build to run on P100's without the patch of #4409. With the patch, like you, running fp16 models (Mistral 7B for example) with no issues.

**Comment by sasha0552** [comment]
> With the patch, like you, running fp16 models (Mistral 7B for example) with no issues.

Not only fp16, but AQLM works well too (#5058)

![image](https://github.com/vllm-project/vllm/assets/45110640/ca8917df-865e-4944-9bd3-270585c51a66)

**Comment by robertgshaw2-neuralmagic** [comment]
> > re: #4409 --> I did not have any issues running an fp16 model on a P40 when I installed from source.
> 
> Hi @robertgshaw2-neuralmagic - was this without the patch? I couldn't get a source build to run on P100's without the patch of #4409. With the patch, like you, running fp16 models (Mistral 7B for example) with no issues.

P40 requires building with the patch.

**Comment by vrdn-23** [comment]
Is there any particular PR that we're waiting for before cutting the release?

**Comment by robertgshaw2-neuralmagic** [comment]
> Is there any particular PR that we're waiting for before cutting the release?

The model support for Phi and Deepseek

**Comment by AmazDeng** [comment]
> > Is there any particular PR that we're waiting for before cutting the release?
> 
> The model support for Phi and Deepseek

Excuse me, when will VLLM support embedding input?

**Comment by dongxiaolong** [comment]
Could we include #4109 ? Structured output is also very important, and it seems almost complete. @simon-mo 

[Link to PR #4109](https://github.com/vllm-project/vllm/pull/4109)

**Comment by LSC527** [comment]
> > Is there any particular PR that we're waiting for before cutting the release?
> 
> The model support for Phi and Deepseek

Hi, is Deepseek v2 supported now?

**Comment by simon-mo** [comment]
Moving Deepseek to optional in #5224
Tracking #4109 as optional in #5224
