### ISSUE TITLE
v0.5.2, v0.5.3, v0.6.0 Release Tracker

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#6434]
### Anything you want to discuss about vllm.

We will make a triplet of releases in the following 3 weeks. 
- [x] v0.5.2 on Monday July 15th. 
- [x] v0.5.3 by Tuesday July 23rd.
- [ ] v0.6.0 after Monday July 29th.

Blockers
- [x] #6463
- [x] #6517
- [x] #6698
- [ ] Test vLLM works with 405B that's `num_kv_heads=8` instead of 16. 

~The reason for such pace is that we want to remove beam search (#6226), which unlocks a suite of scheduler refactoring to enhance performance (async scheduling to overlap scheduling and forward pass for example). We want to release v0.5.2 ASAP to issue warnings and uncover new signals. Then we will decide the removal in v0.6.0. Normally we will deprecate slowly by stretching it by one month or two. However, (1) RFC has been opened for a while (2) it is unfortunately on the critical path of refactoring and performance enhancements.~

Please also feel free to add release blockers. But do keep in mind that I will not slow the release for v0.5.* series unless critical bug.

**Comment by WoosukKwon** [comment]
July 23rd is Tuesday. Do you mean July 24th?

**Comment by simon-mo** [comment]
v0.5.2 has been released: https://github.com/vllm-project/vllm/releases/tag/v0.5.2

**Comment by sasha0552** [comment]
Hello. Can #4409 be included in any of the next releases? Or at least, can I get an explanation as to why it can't be included (maybe I can help in some way?).

Once the wheel size limit increase was approved, and #6394 was merged, wheel size should not be an issue.

I am currently waiting for PyPI staff to approve the wheel size limit increase request to publish the patched `triton` to PyPI (pypi/support#4295).

It would be nice to see support for Pascal GPUs in vLLM. Many people use them because they are cheap.

**Comment by AlphaINF** [comment]
Can this PR be added in v0.5.3?
https://github.com/vllm-project/vllm/pull/5036

**Comment by simon-mo** [comment]
@AlphaINF unlikely given the current state of the PR at the moment (still being reviewed). but I'm looking very much forward to this PR as well!

**Comment by AlphaINF** [comment]
@simon-mo thanks!

**Comment by bohr** [comment]
@simon-mo  for this "async scheduling to overlap scheduling" do we have a plan？

**Comment by AlphaINF** [comment]
hello, when will v0.6.0 release? I'm looking forward to https://github.com/vllm-project/vllm/pull/5036 and MiniCPM-Llama3-V-2_5

**Comment by vrdn-23** [comment]
Would it be possible to get #6594 merged in before the next release is due? @joerunde @Yard1

**Comment by lionheartbeat12** [comment]
#6463 is not available in v0.5.5 docker image. Can you please have it available for 0.6.0?
